### ISSUE TITLE
Not compiling on Mac OS

### ISSUE THREAD

**Issue by crouti** [BenBBear/ionic-cache-src-demo#1]
Downloading and launching with

`ionic run android -l -c`

outputs:

`ERROR running one or more of the platforms: The provided path "/Users/utilisateur/Documents/ionic/ionic-cache-src-demo/platforms/android" is not an Android project.
You may not have the required environment or OS to run this project`

I try to launch on device Samsung GT-P5110 android 4.1

**Comment by crouti** [comment]
solved by removing/adding platform:
`ionic platform rm android`
`ionic platform add android`

but i confirm it does not work no image appear after blue loading circle on device : Samsung GT-P5110 android 4.1

**Comment by mlzxy** [comment]
discuss in another thread.
